apiVersion: v2
name: nginx-custom-selinux
description: NGINX Helm Chart hardened, rootless e compativel com SELinux enforcing
type: application
version: 1.0.0
appVersion: "1.25"
keywords:
- nginx
- selinux
- hardened
- security
- kubernetes
home: https://github.com/luiscorreiaOps/nginx-custom-helm
sources:
- https://github.com/luiscorreiaOps/nginx-custom-helm
maintainers:
- name: Correia
  email: correia.ops@gmail.com
annotations:
  artifacthub.io/category: networking
  artifacthub.io/links: |
    - name: GitHub
      url: https://github.com/luiscorreiaOps/nginx-custom-helm
