apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-custom.fullname" . }}
data:
  nginx.conf.template: |
    worker_processes auto;

    pid /tmp/nginx.pid;

    events {
      worker_connections {{ .Values.nginx.workerConnections }};
    }

    http {
      client_body_temp_path /tmp/client_temp;
      proxy_temp_path       /tmp/proxy_temp;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;

      log_format json escape=json
        '{ "time": "$time_iso8601", '
        '"remote": "$remote_addr", '
        '"method": "$request_method", '
        '"uri": "$request_uri", '
        '"status": "$status", '
        '"bytes": "$body_bytes_sent", '
        '"rt": "$request_time" }';

      access_log /tmp/access.log json;
      error_log  /tmp/error.log warn;

      server {
        listen 8080;

        location / {
          return 200 'NGINX CUSTOM SELINUX OK\n';
        }

        location /health {
          return 200 'OK\n';
        }

        location /metrics {
          return 200 'nginx_up 1\n';
        }
      }
    }
